document.getElementById('hotpink').addEventListener('click',()=>{
    document.getElementsByTagName('body')[0].style.backgroundColor='hotpink'
})
document.getElementById('darkgreen').addEventListener('click',()=>{
    document.getElementsByTagName('body')[0].style.backgroundColor='darkgreen'
})
document.getElementById('blue').addEventListener('click',()=>{
    document.getElementsByTagName('body')[0].style.backgroundColor='blue'
})